import type {
  TuningAxis,
  TuningLoop,
  TuningProposalResponse,
  TuningReviewResponse,
} from '../types/tuning'

type Px4ParamsExportInput = {
  axis: TuningAxis
  loop: TuningLoop
  proposal: TuningProposalResponse
  review?: TuningReviewResponse | null
}

export function buildPx4ParamsFile(input: Px4ParamsExportInput): string {
  const lines = [
    '# Generated by PX4 Log PID Tuning Assistant',
    '# Stage: offline_log_review',
    '# Warning: Validate in SITL before applying to a real vehicle.',
    '# Warning: Do not automatically apply these parameters to a real aircraft.',
    `# Axis: ${input.axis}`,
    `# Loop: ${input.loop}`,
    '',
  ]

  if (input.review?.reviewStatus === 'manual_review_required') {
    lines.splice(
      lines.length - 1,
      0,
      '# Warning: Manual review required before applying these parameters.',
    )
  }

  for (const change of input.proposal.changes) {
    lines.push(`${change.parameter} ${change.to}`)
  }

  return `${lines.join('\n')}\n`
}

type Px4ParamsExportDecisionInput = {
  proposal?: TuningProposalResponse | null
  review?: TuningReviewResponse | null
}

export function shouldAllowParamsExport(
  input: Px4ParamsExportDecisionInput,
): boolean {
  const proposal = input.proposal
  const review = input.review

  return Boolean(
    proposal &&
      proposal.status === 'proposal_generated' &&
      proposal.changes.length > 0 &&
      review?.reviewStatus !== 'rejected' &&
      review?.riskLevel !== 'high',
  )
}

export function getPx4ParamsExportHint(
  input: Px4ParamsExportDecisionInput,
): string {
  const proposal = input.proposal
  const review = input.review

  if (!proposal) {
    return '请先生成候选参数。'
  }
  if (proposal.status === 'rejected') {
    return '当前候选参数已被拒绝，不能导出 PX4 参数文件。'
  }
  if (review?.reviewStatus === 'rejected') {
    return 'Safety / AI Review 已拒绝该建议，不能导出 PX4 参数文件。'
  }
  if (review?.riskLevel === 'high') {
    return 'Safety / AI Review 风险等级高，不能导出 PX4 参数文件。'
  }
  if (proposal.status !== 'proposal_generated' || proposal.changes.length === 0) {
    return '当前没有可导出的参数变更。'
  }
  return ''
}

export function downloadPx4ParamsFile(content: string, filename: string): void {
  const blob = new Blob([content], {
    type: 'text/plain;charset=utf-8',
  })
  const objectUrl = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = objectUrl
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(objectUrl)
}
