import { describe, expect, it } from 'vitest'
import type {
  TuningProposalResponse,
  TuningReviewResponse,
} from '../types/tuning'
import {
  buildPx4ParamsFile,
  shouldAllowParamsExport,
} from './px4ParamsExport'

function createProposal(
  overrides?: Partial<TuningProposalResponse>,
): TuningProposalResponse {
  return {
    status: 'proposal_generated',
    axis: 'roll',
    loop: 'rate',
    parameterNames: {
      p: 'MC_ROLLRATE_P',
      i: 'MC_ROLLRATE_I',
      d: 'MC_ROLLRATE_D',
    },
    changes: [
      {
        key: 'p',
        parameter: 'MC_ROLLRATE_P',
        from: 0.15,
        to: 0.1425,
        changePercent: -5,
        reasonCode: 'HIGH_OVERSHOOT',
        reason: 'Overshoot is high, reduce P conservatively.',
      },
      {
        key: 'd',
        parameter: 'MC_ROLLRATE_D',
        from: 0.003,
        to: 0.00315,
        changePercent: 5,
        reasonCode: 'ADD_DAMPING_AFTER_OVERSHOOT',
        reason: 'Add damping conservatively.',
      },
    ],
    unchanged: [
      {
        key: 'i',
        parameter: 'MC_ROLLRATE_I',
        value: 0.2,
        reason: 'No strong evidence for changing I.',
      },
    ],
    warnings: [],
    ...overrides,
  }
}

function createReview(
  overrides?: Partial<TuningReviewResponse>,
): TuningReviewResponse {
  return {
    reviewStatus: 'manual_review_required',
    riskLevel: 'medium',
    summary: 'Manual review required before any real-world use.',
    concerns: [],
    recommendations: [],
    warnings: [],
    ...overrides,
  }
}

describe('px4ParamsExport', () => {
  it('exports only proposal changes and omits unchanged parameters', () => {
    const content = buildPx4ParamsFile({
      axis: 'roll',
      loop: 'rate',
      proposal: createProposal(),
    })

    expect(content).toContain('MC_ROLLRATE_P 0.1425')
    expect(content).toContain('MC_ROLLRATE_D 0.00315')
    expect(content).not.toContain('MC_ROLLRATE_I 0.2')
  })

  it('includes required safety warnings in the file header', () => {
    const content = buildPx4ParamsFile({
      axis: 'roll',
      loop: 'rate',
      proposal: createProposal(),
    })

    expect(content).toContain('# Generated by PX4 Log PID Tuning Assistant')
    expect(content).toContain(
      '# Warning: Validate in SITL before applying to a real vehicle.',
    )
    expect(content).toContain(
      '# Warning: Do not automatically apply these parameters to a real aircraft.',
    )
  })

  it('returns false for rejected proposals', () => {
    expect(
      shouldAllowParamsExport({
        proposal: createProposal({ status: 'rejected', changes: [] }),
        review: null,
      }),
    ).toBe(false)
  })

  it('returns false when reviewStatus is rejected', () => {
    expect(
      shouldAllowParamsExport({
        proposal: createProposal(),
        review: createReview({ reviewStatus: 'rejected', riskLevel: 'high' }),
      }),
    ).toBe(false)
  })

  it('returns false when riskLevel is high', () => {
    expect(
      shouldAllowParamsExport({
        proposal: createProposal(),
        review: createReview({ reviewStatus: 'manual_review_required', riskLevel: 'high' }),
      }),
    ).toBe(false)
  })

  it('keeps current strategy for manual_review_required / medium and marks the file', () => {
    const proposal = createProposal()
    const review = createReview({
      reviewStatus: 'manual_review_required',
      riskLevel: 'medium',
    })

    expect(
      shouldAllowParamsExport({
        proposal,
        review,
      }),
    ).toBe(true)

    const content = buildPx4ParamsFile({
      axis: 'roll',
      loop: 'rate',
      proposal,
      review,
    })

    expect(content).toContain(
      '# Warning: Manual review required before applying these parameters.',
    )
  })
})
